ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
obj-$(CONFIG_MSM_CAMERA_SENSOR_RHM_OIS_ACTUATOR) += OIS_func.o
obj-$(CONFIG_MSM_CAMERA_SENSOR_RHM_OIS_ACTUATOR) += OIS_user.o
