subdir-ccflags-$(CONFIG_ARCH_MSM) += -Iarch/arm/mach-msm

obj-$(CONFIG_MACH_SHENQI_K9) += board-8974-k9.o
obj-$(CONFIG_MACH_SHENQI_K9) += board-8974-k9-gpiomux.o

obj-$(CONFIG_MACH_SHENQI_K9) += clock-krait-8974-k9.o clock-8974-k9.o

obj-$(CONFIG_MACH_SHENQI_K9) += shenqi_nv.o
